### ISSUE TITLE
NoMethodError for child.name

### ISSUE THREAD

**Issue by aercolino** [troessner/reek#1158]
Reek version 4.5.3

Admittedly unusual code in the line that caused the exception (found by debugging with RubyMine):

```
attr_accessor *(booleans = [ :obfuscated, :another_obfuscated, :yet_another_obfuscated ])
```

Output

```
      Source app/models/obfuscated_file.rb can not be processed by Reek.

      This is most likely either a bug in your Reek configuration (config file or
      source code comments) or a Reek bug.

      Please double check your Reek configuration taking the original exception
      below into account -  you might have misspelled a smell detector for instance.
      (In the future Reek will handle configuration errors more gracefully, something
      we are working on already).

      If you feel that this is not a problem with your Reek configuration but with
      Reek itself it would be great if you could report this back to the Reek
      team by opening up a corresponding issue at https://github.com/troessner/reek/issues.

      Please make sure to include the source in question, the Reek version
      and the original exception below.

      Exception message:

      undefined method `name' for #<#<Class:0x0000010b485290>:0x0000010b485218>

      Original exception:

      /Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context/visibility_tracker.rb:26:in `block in track_visibility'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context/visibility_tracker.rb:25:in `each'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context/visibility_tracker.rb:25:in `track_visibility'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context/module_context.rb:83:in `track_visibility'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:511:in `handle_send_for_modules'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:156:in `process_send'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:63:in `build'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `each'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `process'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:286:in `process_begin'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:63:in `build'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `each'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `process'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:286:in `process_begin'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:63:in `build'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `each'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:73:in `process'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:80:in `block in process_module'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:490:in `inside_new_context'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:79:in `process_module'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:63:in `build'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/context_builder.rb:30:in `initialize'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/examiner.rb:142:in `new'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/examiner.rb:142:in `examine_tree'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/examiner.rb:122:in `run'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/examiner.rb:87:in `smells'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/examiner.rb:103:in `smelly?'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/report/formatter/progress_formatter.rb:43:in `progress'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/report/text_report.rb:21:in `add_examiner'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/cli/command/report_command.rb:23:in `each'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/cli/command/report_command.rb:15:in `execute'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/lib/reek/cli/application.rb:29:in `execute'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/gems/reek-4.5.3/bin/reek:13:in `<top (required)>'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/bin/reek:23:in `load'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/bin/reek:23:in `<main>'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/aercolino/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by troessner** [comment]
Given the code itself this bug seems to be quite an edge case ;)
Thanks for the report though - we should fix this nevertheless of course.

**Comment by mvz** [comment]
I cannot reproduce this with Reek 4.7.1. We did fix several `child.name` problems along the way, so I think we accidentally fixed this one as well.
