### ISSUE TITLE
Enable validation of our configuration via yaml schema

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1317]
Inspired by [this blog post](https://blog.picnic.nl/how-to-use-yaml-schema-to-validate-your-yaml-files-c82c049c2097) I added a first "very WIP" branch [here](https://github.com/troessner/reek/pull/1316) which I would like to pursue after we have done #1078 - thoughts?

**Comment by troessner** [comment]
I hit a snag. This spec in configuration_file_finder_spec

```Ruby
    context 'schema validation' do
      it 'works even with ruby-regex in the configuration file' do
        expected = {
          'UnusedPrivateMethod' => { 'enabled' => true, 'exclude' => /foobar/ }
        }
        configuration = described_class.load_from_file(CONFIG_PATH.join('ruby_regex.reek'))
        expect(configuration).to eq(expected)
      end
    end
```

with this config file:

```Yaml
---
UnusedPrivateMethod:
  enabled: true
  exclude:
    - !ruby/regexp /(.*)wesome#foo(.*)/
```

 will crash Rx:

```

Failures:

  1) Reek::Configuration::ConfigurationFileFinder.load_from_file schema validation works even with ruby-regex in the configuration file
     Failure/Error: raise Errors::ConfigFileException, "Invalid configuration file: #{error.message}"

     Reek::Errors::ConfigFileException:
       Invalid configuration file: expected String got /(.*)wesome#foo(.*)/ (/rec:'UnusedPrivateMethod')
     # ./lib/reek/configuration/schema_validator.rb:28:in `rescue in validate'
     # ./lib/reek/configuration/schema_validator.rb:26:in `validate'
     # ./lib/reek/configuration/schema_validator.rb:22:in `validate'
     # ./lib/reek/configuration/configuration_file_finder.rb:68:in `load_from_file'
     # ./spec/reek/configuration/configuration_file_finder_spec.rb:106:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Rx::ValidationError:
     #   expected String got /(.*)wesome#foo(.*)/ (/rec:'UnusedPrivateMethod')
     #   ./lib/ext/Rx.rb:603:in `check!'

Finished in 0.00306 seconds (files took 1.36 seconds to load)
1 example, 1 failure
```

I never was a huge fan of using "!ruby/regexp" in our yaml files and it's understandable, that parsers do not tolerate this. 

What do you think about getting rid of this, i.e. just using strings and converting them regexes after we loaded the file?

**Comment by chastell** [comment]
I like the idea of config files without Ruby-specific classes.

I’m not sure how backward-(in)compatible would be to try to guess whether a given string is a name or a regex, but maybe we could just go with a simple heuristic to the tune of _strings starting and ending with `/` are always regexes_.

**Comment by mvz** [comment]
@chastell yes, that could be an option.
