### ISSUE TITLE
uninitialized constant Reek::Errors::ConfigFileException

### ISSUE THREAD

**Issue by crevete** [troessner/reek#1383]
When I launch reek 5.0, I've got the following exception : 
```
....../gems/reek-5.0.0/lib/reek/configuration/configuration_file_finder.rb:62:in `rescue in load_from_file': uninitialized constant Reek::Errors::ConfigFileException (NameError)
Did you mean?  Reek::Errors::ConfigFileError
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/lib/reek/configuration/configuration_file_finder.rb:59:in `load_from_file'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/lib/reek/configuration/configuration_file_finder.rb:32:in `find_and_load'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/lib/reek/configuration/app_configuration.rb:30:in `from_path'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/lib/reek/cli/application.rb:45:in `configure_app_configuration'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/lib/reek/cli/application.rb:23:in `initialize'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/bin/reek:12:in `new'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/gems/reek-5.0.0/bin/reek:12:in `<top (required)>'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/bin/reek:23:in `load'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/bin/reek:23:in `<main>'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/bin/ruby_executable_hooks:15:in `eval'
	from /home/xsun/.rvm/gems/ruby-2.4.3@fftserver1/bin/ruby_executable_hooks:15:in `<main>'
```
I would say that is a bug, because ```Reek::Errors::ConfigFileException``` does not exist in the gem, but ```Reek::Errors::ConfigFileError``` does.

**Comment by troessner** [comment]
Oh my, I'd say we have a pretty extensive test coverage and we *still* missed that. 
Fix underway, thanks for reporting!

**Comment by crevete** [comment]
@troessner I confirm that it works fine with 5.0.1. Thanks :-)
