### ISSUE TITLE
Unterminated string meets end of file

### ISSUE THREAD

**Issue by peterjgordon** [troessner/reek#1403]
All files appear to have this exception when reek is executed on our CI environment as a GitLab CI Job (works fine locally).
* It runs in this docker container: `ruby:2.4.4` (https://hub.docker.com/r/_/ruby/). 
* This is the rake task I was using to allow verbose output:
```
require 'reek/rake/task'
Reek::Rake::Task.new do |t|
  t.config_file = '.reek.yml'
  t.source_files = '.'
  t.verbose = true
end
```
`.reek.yml` just excludes `db/migrate`. This is run as `bundle exec rake reek` in the docker container.

Do you have any idea why this error would be occuring? Even pointers to help with debugging this would help!

    Exception message:

    #<Parser::SyntaxError: unterminated string meets end of file>

    Original exception:

    /ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/diagnostic/engine.rb:73:in `process'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/lexer.rb:22982:in `diagnostic'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/lexer.rb:11359:in `advance'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/base.rb:228:in `next_token'
	/usr/local/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	/usr/local/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/base.rb:167:in `parse'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/parser-2.5.1.2/lib/parser/base.rb:184:in `parse_with_comments'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/source/source_code.rb:131:in `parse'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/source/source_code.rb:91:in `parse_result'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/source/source_code.rb:76:in `syntax_tree'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:120:in `syntax_tree'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:124:in `examine_tree'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:101:in `block in run'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:110:in `wrap_exceptions'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:100:in `run'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:68:in `smells'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/examiner.rb:76:in `smells_count'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/report/base_report.rb:48:in `add_examiner'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/report/text_report.rb:23:in `add_examiner'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/cli/command/report_command.rb:25:in `each'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/cli/command/report_command.rb:17:in `execute'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/lib/reek/cli/application.rb:29:in `execute'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/gems/reek-4.8.2/bin/reek:14:in `<top (required)>'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/bin/reek:23:in `load'
	/ROOT_PATH_GOES_HERE/vendor/bundle/ruby/2.4.0/bin/reek:23:in `<main>'

**Comment by mvz** [comment]
Can you please also paste the bit above `Exception message:`?

**Comment by peterjgordon** [comment]
Source vendor/bundle/ruby/2.4.0/gems/activejob-5.1.6/lib/rails/generators/job/templates/job.rb cannot be processed by Reek.

    This is most likely a Reek bug.

    It would be great if you could report this back to the Reek team by opening a
    corresponding issue at https://github.com/troessner/reek/issues.

    Please make sure to include the source in question, the Reek version and the
    original exception below.

**Comment by mvz** [comment]
Ah! That file is a template so indeed does not contain valid Ruby. It's probably best to also exclude `vendor/` in `.reek.yml`.

**Comment by mvz** [comment]
We probably shouldn't say 'This is most likely a Reek bug' when the underlying error is `Parser::SyntaxError`.

**Comment by peterjgordon** [comment]
Yeah, would probably help to point to paths you should exclude in the readme or something.

**Comment by mvz** [comment]
It's hard to make a blanket statement about that since it depends on the project and in this case even on the CI environment.

**Comment by mvz** [comment]
@peterjgordon which version of Reek are you using? I'm expecting a different error to be raised in this case.
