### ISSUE TITLE
Calls to super with parameter and block gives error

### ISSUE THREAD

**Issue by huerlisi** [troessner/reek#404]
The following code gives an error:

```ruby
class Thing
  def foo
    super(options) do
    end
  end
end
```

This is the output:

```
shuerlimann@tom:~$ reek a.rb 
/home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:73:in `ignored_iterator?': undefined method `method_name' for (super (NoMethodError)
  (send nil :options)):#<Class:0x007f1eb7c60570>
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:65:in `find_iters_for_iter_node'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:60:in `block in find_iters'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `flat_map'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `find_iters'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:54:in `find_deepest_iterator'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:35:in `examine_context'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/smells/smell_detector.rb:89:in `examine'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:59:in `block in examine'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:58:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:58:in `examine'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:161:in `check_smells'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:155:in `block in inside_new_context'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:167:in `push'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:153:in `inside_new_context'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:41:in `process_def'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `block in process_default'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `process_default'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:34:in `block in process_module'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:154:in `block in inside_new_context'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:167:in `push'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:153:in `inside_new_context'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:33:in `process_module'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/core/sniffer.rb:20:in `report_on'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/examiner.rb:41:in `block in initialize'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/source/source_repository.rb:41:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/source/source_repository.rb:41:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/examiner.rb:39:in `initialize'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/cli/reek_command.rb:13:in `new'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/cli/reek_command.rb:13:in `block in execute'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/cli/reek_command.rb:12:in `each'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/cli/reek_command.rb:12:in `execute'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/lib/reek/cli/application.rb:32:in `execute'
        from /home/shuerlimann/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/reek-1.6.5/bin/reek:11:in `<top (required)>'
        from /home/shuerlimann/.rbenv/versions/2.2.0/bin/reek:23:in `load'
        from /home/shuerlimann/.rbenv/versions/2.2.0/bin/reek:23:in `<main>'
```

**Comment by huerlisi** [comment]
Seems similar to #379

**Comment by mvz** [comment]
Hi @huerlisi, can you try upgrading to reek 2.0 or at least 1.6.6?

**Comment by troessner** [comment]
I can confirm that this error happens with both 2.0.1 and 1.6.6 as well:

1.6.6:

>> 
  ( $ ) reek -v
reek 1.6.6
  ( $ ) reek foo.rb 
/home/timo/.rvm/gems/ruby-2.1.1/gems/reek-1.6.6/lib/reek/smells/nested_iterators.rb:73:in `ignored_iterator?': undefined method `method_name' for (super (NoMethodError)
  (send nil :options)):#<Class:0x00000003650560>
	from /home/timo/.rvm/gems/ruby-2.1.1/gems/reek-1.6.6/lib/reek/smells/nested_iterators.rb:65:in `find_iters_for_iter_node'

2.0.1:

>>   ( $ ) reek foo.rb 
/home/timo/.rvm/gems/ruby-2.1.1/gems/reek-2.0.1/lib/reek/smells/nested_iterators.rb:73:in `ignored_iterator?': undefined method `method_name' for (super (NoMethodError)
  (send nil :options)):#<Class:0x00000002d4c0e0>
	from /home/timo/.rvm/gems/ruby-2.1.1/gems/reek-2.0.1/lib/reek/smells/nested_iterators.rb:65:in `find_iters_for_iter_node'
