### ISSUE TITLE
Reek fails on methods with unpacked parameters – undefined method `optional_argument?' for (mlhs (NoMethodError) ...

### ISSUE THREAD

**Issue by amiryal** [troessner/reek#502]
Hi,

See [official Ruby documentation](http://ruby-doc.org/core-2.2.0/doc/syntax/methods_rdoc.html#label-Array+Decomposition) for why this syntax is valid.

To reproduce the failure:
```
cat <<-EOF > test.rb
def meth(param1, (param2_a, param2_b))
  puts param1, param2_a, param2_b
end
meth('1', ['2_a', '2_b'])
EOF

ruby test.rb
reek test.rb
```

The output on my workstation (Ruby `2.2.1`, Reek `2.1.0`):
```
$ cat <<-EOF > test.rb
> def meth(param1, (param2_a, param2_b))
>   puts param1, param2_a, param2_b
> end
> meth('1', ['2_a', '2_b'])
> EOF
$ 
$ ruby test.rb
1
2_a
2_b
$ reek test.rb
/home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:13:in `block in default_assignments': undefined method `optional_argument?' for (mlhs (NoMethodError)
  (arg :param2_a)
  (arg :param2_b)):#<Class:0x00000001ed49e0>
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:12:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:12:in `default_assignments'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/smells/boolean_parameter.rb:25:in `examine_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/smells/smell_detector.rb:92:in `examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:36:in `block in examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:35:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:35:in `examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:169:in `check_smells'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:163:in `block in inside_new_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:175:in `push'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:161:in `inside_new_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:45:in `process_def'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:23:in `process'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:32:in `block in process_default'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:31:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:31:in `process_default'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:97:in `process_begin'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:23:in `process'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:64:in `block in run'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/source/source_repository.rb:40:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/source/source_repository.rb:40:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:61:in `run'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:32:in `initialize'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:13:in `new'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:13:in `block in execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:12:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:12:in `execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/application.rb:32:in `execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/bin/reek:11:in `<top (required)>'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/reek:23:in `load'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/reek:23:in `<main>'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/ruby_executable_hooks:15:in `eval'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/ruby_executable_hooks:15:in `<main>'
```

Thanks for taking the time to look into this.

Yours,
Amir

**Comment by mvz** [comment]
Cool syntax :smile:. Should not be hard to fix.
