### ISSUE TITLE
Reek fails on use of ||= with constants

### ISSUE THREAD

**Issue by ehedrick** [troessner/reek#622]
I ran into an issue with the use of the or equals operator on constants.

Example file (test.rb):
```ruby
module Foo
  FOO ||= :foo
end
```

Output of ```reek test.rb```:
```
$ reek test.rb
/Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/ast/sexp_extensions.rb:408:in `defines_module?': undefined method `type' for :FOO:Symbol (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:54:in `process_casgn'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:38:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:77:in `block in process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:40:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:77:in `block in process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:76:in `process_default'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:47:in `block in process_module'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:191:in `block in inside_new_context'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:199:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:190:in `inside_new_context'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:46:in `process_module'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:38:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/tree_walker.rb:27:in `walk'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/examiner.rb:73:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/examiner.rb:35:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:14:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/reek_command.rb:13:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/lib/reek/cli/application.rb:34:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/reek-3.1/bin/reek:11:in `<top (required)>'
	from /usr/bin/reek:23:in `load'
	from /usr/bin/reek:23:in `<main>'
```

**Comment by troessner** [comment]
Interesting. Confirmed.
I'll look into it, thanks for the report!

**Comment by HParker** [comment]
Interestingly I am seeing the same issue when assigning multiple constants at once:
```Ruby
NONE_ID, OTHER_ID = '-1', 'nil'
```

changing this to
```ruby
 NONE_ID = '-1'
  OTHER_ID = 'nil'
```
fixes the issue. 

I can include a stack trace, but it is the same as above except for the `:FOO:Symbol` bit.

**Comment by troessner** [comment]
Fixed, closing this.
