### ISSUE TITLE
Single smell option broken

### ISSUE THREAD

**Issue by mvz** [troessner/reek#682]
It seems reek checks the config against the current set in the smell repository rather than the set of all existing detectors:

```
[matijs@walnut] reek --smell UtilityFunction lib
/home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/smells/smell_repository.rb:30:in `configure': Unknown smell type Reek::Smells::UncommunicativeMethodName found in configuration (ArgumentError)
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/smells/smell_repository.rb:24:in `block in initialize'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/smells/smell_repository.rb:23:in `each'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/smells/smell_repository.rb:23:in `initialize'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/examiner.rb:71:in `new'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/examiner.rb:71:in `run'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/examiner.rb:35:in `initialize'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/cli/reek_command.rb:14:in `new'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/cli/reek_command.rb:14:in `block in execute'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/cli/reek_command.rb:13:in `each'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/cli/reek_command.rb:13:in `execute'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/lib/reek/cli/application.rb:34:in `execute'
	from /home/matijs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.2.1/bin/reek:12:in `<top (required)>'
	from /home/matijs/.rbenv/versions/2.2.3/bin/reek:23:in `load'
	from /home/matijs/.rbenv/versions/2.2.3/bin/reek:23:in `<main>'
```

**Comment by troessner** [comment]
Confirmed.

Additional details: I checked our cucumber features if we had a test for this and we do: https://github.com/troessner/reek/blob/master/features/command_line_interface/smell_selection.feature

Interestingly enough, when I use that in my console:

```
  ( $ ) pwd
/tmp
  ( $ ) cat smelly.rb 
    # smelly class for testing purposes
    class Smelly
      def m
        puts @foo.bar
        puts @foo.bar
      end
    end
  ( $ ) reek  --smell UncommunicativeMethodName smelly.rb
smelly.rb -- 1 warning:
  [3]:Smelly#m has the name 'm' (UncommunicativeMethodName)
```

this works. Seems like a non-trivial problem that also indicates that there is something wrong with our cli feature set up if it doesn't catch bugs like that.

**Comment by mvz** [comment]
This was accidentally fixed in master and is now ensured through a cucumber scenario.

**Comment by troessner** [comment]
>> This was accidentally fixed in master

Ah, the best way possible :laughing:
