### ISSUE TITLE
Crash on invalid syntax

### ISSUE THREAD

**Issue by troessner** [troessner/reek#859]
Coming from here https://github.com/AtomLinter/linter-reek/issues/35

```Ruby
class Create
  def self.

  end
end
```

gives me:

```
reek ~/Desktop/foo.rb
/Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:121:in `[]=': 1...1 out of range (RangeError)
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:121:in `render_line'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:96:in `render'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:89:in `block in default_parser'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic/engine.rb:67:in `call'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic/engine.rb:67:in `process'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:251:in `on_error'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:162:in `parse'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:180:in `parse_with_comments'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:50:in `parse_with_comments'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/source/source_code.rb:84:in `syntax_tree'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/examiner.rb:76:in `run'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/examiner.rb:37:in `initialize'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/cli/reek_command.rb:13:in `new'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/cli/reek_command.rb:13:in `block in execute'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/cli/reek_command.rb:12:in `each'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/cli/reek_command.rb:12:in `execute'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/lib/reek/cli/application.rb:27:in `execute'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/reek-3.9.1/bin/reek:12:in `<top (required)>'
	from /Users/timo/.rbenv/versions/2.2.3/bin/reek:23:in `load'
```

This shouldn't let `Reek` crash, especially since we're actually [rescuing](https://github.com/troessner/reek/blob/master/lib/reek/source/source_code.rb#L84) those kind of problems. 
Seems like something changed in `parser`.

**Comment by mvz** [comment]
Parser should raise a more meaningful error here, **and** we should handle its failure to do so in this case.

**Comment by troessner** [comment]
Filed an [issue for this](https://github.com/whitequark/parser/issues/273)
